// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOdaWAvRcSEkY1u0-NW6y6xv3zSGBP6s',
    appId: '1:153389146287:android:335638c5413daa4ce6745a',
    messagingSenderId: '153389146287',
    projectId: 'parking-app-cd0f0',
    databaseURL: 'https://parking-app-cd0f0-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-cd0f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxYzuXsDgKhwSxKK6AWXYIf8V8oh_bxQ',
    appId: '1:153389146287:ios:5ef12a47b5748790e6745a',
    messagingSenderId: '153389146287',
    projectId: 'parking-app-cd0f0',
    databaseURL: 'https://parking-app-cd0f0-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-cd0f0.appspot.com',
    iosClientId: '153389146287-8pfb72rc5a4vkg5tdtlqt1ea6edvg06u.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingApp',
  );

}